services:
    # Mysql database container
    db:
        image: mysql
        container_name: adminbundle_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - adminbundle

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: adminbundle_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - adminbundle

    php:
        container_name: adminbundle_php
        build:
            context: ./docker
            dockerfile: Dockerfile-php
        volumes:
            - ../:/var/www
        networks:
            - adminbundle

    nginx:
        container_name: adminbundle_nginx
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        volumes:
            - ../:/var/www
        depends_on:
            - php
        ports:
            - 8000:80
        networks:
            - adminbundle

networks:
    adminbundle:

volumes:
    db-data:
    symfony_app_var:
    symfony_app_vendor:

