controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

aropixel_admin:
    resource: '@AropixelAdminBundle/Resources/config/routing/admin.yml'
    prefix: /admin

aropixel_admin_download:
    resource: "@AropixelAdminBundle/Resources/config/routing/download.yml"

aropixel_page:
    resource: '@AropixelPageBundle/Resources/config/routing.yml'
    prefix: /admin

aropixel_blog:
    resource: '@AropixelBlogBundle/Resources/config/routing.yml'
    prefix: /admin

aropixel_menu:
    resource: '@AropixelMenuBundle/Resources/config/routing.xml'
    prefix: /admin
