services:
    # Mysql database container
    db:
        image: mysql
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - adminbundle

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - adminbundle

    php:
        build:
            context: services/php
        volumes:
            - ../../app:/var/www
        networks:
            - adminbundle

    nginx:
        build:
            context: services/nginx
        volumes:
            - ../../app:/var/www
        depends_on:
            - php
        ports:
            - 8000:80
        networks:
            - adminbundle

networks:
    adminbundle:

volumes:
    db-data:
    symfony_app_var:
    symfony_app_vendor:

