imports:
  - { resource: "@AropixelAdminBundle/Resources/config/app/config.yml" }

aropixel_admin:
  client:
    name: "App"
  copyright:
    name: "Aropixel"
    link: "https://www.aropixel.com/"
  theme:
    menu_position: left

aropixel_menu:
  cache: 0
  menus:
    navbar:
      name: Menu principal
      depth: 2
      strict_mode: true
      required_pages:
        homepage: "Page d'accueil"
    footer:
      name: Footer
      depth: 2
      strict_mode: true
